### ISSUE TITLE
Question about tabs

### ISSUE THREAD

**Issue by nbieberitz** [SergeyMC9730/triggersearch#2]
Why are there so many different tabs?
![Screenshot_20241001_164124_Geode](https://github.com/user-attachments/assets/ba64aff1-c967-4130-8c8c-2fe063b6563c)

**Comment by SergeyMC9730** [comment]
That's definitely a bug on Android... Will try to fix in v1.0.2

**Comment by DemiSans** [comment]
@SergeyMC9730 on pc too

**Comment by nbieberitz** [comment]
Ok, please do. Thanks!

**Comment by SergeyMC9730** [comment]
Seems to be fixed in 1.0.3
